### ISSUE TITLE
How to send commands like KICK, ME, STAT, etc.

### ISSUE THREAD

**Issue by silverbucket** [ircanywhere/irc-factory#32]
Hey, I've been trying to figure out how to send `/` commands. Like `/me` `/kick` etc.

I tried using the RAW interface, ie: `[ME, '#channel', 'does computering']`

But that doesn't work. However with `KICK` it does: `[KICK, '#channel', 'annoyingperson']`

So, how can we send `ME` commands? and is there a way to uniformly handle all `/` commands?

**Comment by rickihastings** [comment]
/me isn't actually a standard IRC command, it's implemented by most clients but underneath it's just a PRIVMSG.

If you take a look at https://github.com/ircanywhere/irc-factory/wiki/Setup-&-Usage and look for Client.me you'll see a function call for it.

**Comment by silverbucket** [comment]
Ah, of course, must have overlooked that, thanks!
